url: "https://ashorthike-de.fuly.network"
title: "A Short Hike - German Translation - Fox Network"
description: "Unofficial German translation for the game A Short Hike 🍂"
reportUrl: "https://forms.fuly.network/ashorthike-translation-typo"
contactUrl: "https://fuly.network/contact"
donateUrl: "./donate"
youtubeVideoId: "l4bWwobx_LQ"
downloads:
  - name: "Version 1.8 - 1.9"
    date: "16 May 2022"
    url: "/downloads/LANG_German.yarn_lines.csv"
  - name: "Version 1.4"
    date: "16 May 2022"
    url: "/downloads/MountainQuest.yarn.txt"
